name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LINODE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.LINODE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Linode
        env:
          LINODE_HOST: ${{ secrets.LINODE_HOST }}
          LINODE_USER: ${{ secrets.LINODE_USER }}
        run: |
          ssh -T -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $LINODE_USER@$LINODE_HOST << 'EOF'
            set -e
            echo "=== Starting deployment on Linode ==="

            # Go to project directory (use your folder)
            cd ~/main || mkdir -p ~/main && cd ~/main

            # Pull or clone
            if [ -d ".git" ]; then
              echo "Pulling latest changes..."
              git pull origin main
            else
              echo "Fresh clone..."
              git clone https://github.com/${GITHUB_REPOSITORY}.git . -b main
            fi

            echo "Updating Maven..."
            sudo apt update -y
            sudo apt install -y maven

            echo "Building project..."
            mvn -f pom.xml clean package

            echo "Restarting app..."
            mkdir -p logs  
            pkill -f 'java -jar' || true
            nohup java -jar main/target/*-jar-with-dependencies.jar > logs/app.log 2>&1 &
            echo "Deployment successful!"
          EOF
