name: Deploy to Linode (Maven + .env + DB)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup SSH so we can connect to your Linode
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.LINODE_HOST }} >> ~/.ssh/known_hosts

      # 3️⃣ Deploy your project to Linode
      - name: Deploy to Linode
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.LINODE_USER }}@${{ secrets.LINODE_HOST }} "
            # --- Go to your app directory (create if missing)
            cd ~/app || mkdir -p ~/app && cd ~/app

            # --- Clone or update your repo
            if [ ! -d .git ]; then
              git clone https://github.com/${{ github.repository }}.git .
            else
              git fetch origin main
              git reset --hard origin/main
            fi

            # --- Preserve existing .env file
            [ -f .env ] && echo '.env preserved'

            # --- Make sure logs folder exists
            mkdir -p logs

            # --- Build your Java project (Maven)
            cd ~/app && mvn clean package -DskipTests

            # --- Restart the Telegram bot
            pkill -f 'java -jar' || true
            nohup java -jar target/*.jar > logs/bot.log 2>&1 &
          "
